env:
  browser: true
  es2021: true
  node: true
  jest/globals: true
extends:
  - eslint:recommended
  - plugin:jest/recommended
  - prettier
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  babelOptions:
    plugins:
      - '@babel/plugin-syntax-import-assertions'
plugins:
  - jest
<<<<<<< HEAD
rules: {
=======
rules:
>>>>>>> 602719ed792855ae344c6d167e8bc3822b1c7172
  no-unused-vars: warn
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/prefer-to-have-length: warn
  jest/valid-expect: error
